eureka:
  client:
    serviceUrl:
      #defaultZone: http://39.105.114.254:666/eureka/
      defaultZone: http://101.132.180.235:7776/eureka/
server:
  port: 8112
  pn-user-provider:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
spring:
   application:
      name: pn-user-consumer
feign:
  hystrix:
    enabled: true  # 开启容错


